---

- hosts: all
  vars:
    # Arch's default python is python3
    ansible_python_interpreter: "/usr/bin/env python2"

  handlers:

    - name: locale-regen
      command: locale-gen

    - name: mkinitcpio
      command: mkinitcpio -p linux
      notify: mkinitcpio-mainline

    - name: mkinitcpio-mainline
      command: mkinitcpio -p linux-mainline
      args:
        removes: /etc/mkinitcpio.d/linux-mainline.preset

  roles:

    - console
    - systemd-boot
    - network
    - { role: aur, aur_package_name: packer }
    - bluetooth

  tasks:

    - name: Set the correct timezone
      file:
        src: /usr/share/zoneinfo/Europe/Stockholm
        dest: /etc/localtime
        state: link

    - name: Setup mkinitcpio.conf
      template:
        src: templates/mkinitcpio.conf.j2
        dest: /etc/mkinitcpio.conf
      notify: mkinitcpio

    - name: Setup makepkg.conf
      template:
        src: templates/makepkg.conf.j2
        dest: /etc/makepkg.conf

    - name: Install packages
      pacman: name={{ item }}
      with_items:

        # For the system
        - intel-ucode
        - linux-firmware

        # For the shell needs
        - vim
        - pkgfile
        - extra/bash-completion

        # A DE is nice ...
        - gnome
        - gnome-extra
        - gnome-shell
        - gnome-software

        # X
        - extra/xorg-xinit
        #- extra/xf86-video-intel use: xf86-video-intel-git from aur
        - core/kmod
