---


- name: Setup locale.conf
  template:
    src: locale.conf.j2
    dest: /etc/locale.conf
  notify: locale-regen

- name: Setup vconsole.conf
  template:
    src: vconsole.conf.j2
    dest: /etc/vconsole.conf

